### PR TITLE
use the BSD getopt() on Windows

### PR DESCRIPTION
**Pull request by janstary**
Windows does not have getopt(), so say that in sysdep.h,
declare the function and the helper vars, and provide
compat-getopt.c as with the other compats. A trivial
have-getopt.c sets HAVE_GETOPT on UNIX.

### CODE REVIEW

**Comment by janstary** [comment]
The implementation is taken from OpenBSD 6.3.
Please test on windows.

**Comment by janstary** [comment]
Does not break on OpenBSD, Debian, Ubuntu, Solaris, MacOS.

**Comment by janstary** [comment]
squashed

**Comment by janstary** [comment]
merged master to stay out of conflict

**Comment by mcd500** [comment]
The getopt() from OpenBSD 6.3 is great.
I just tried on Win.
The two header files bellow required in compat-getopt.c do not seem to be in the repository.
#include <err.h>
#include <getopt.h>
Do you mind creating patches for it?

**Comment by mcd500** [comment]
Thank you, great!

**Comment by janstary** [comment]
Does that mean it compiles now?

**Comment by mcd500** [comment]
Yes, compiles perfectly. 👍

**Pull request merged**
