### PR TITLE
update the homepage: html manages, fixed emails

### PR DESCRIPTION
**Pull request by janstary**
This is a revision of the RTPTools homepage.
Instead of quoting the manpages almost in full, link to the html versions.
Link to the git repo and to the README.
Fix some old non-functional emails.

### CODE REVIEW

**Comment by janstary** [comment]
Come to think of it, don't we want https://github.com/columbia-irt/rtptools/ itself
to be the actual homepage? It's almost all there in the README, and rtptools.html's
content could be just merged into it.

**Comment by mcd500** [comment]
I changed the file name from rtptools.html to rtptools.html.in for maintainability.

I would like to keep the html changes minimum for the next 1.22 release and
consider the coloration of html hosted on http://www.cs.columbia.edu/irt/software/rtptools/ and
github in the future release.

And prefer to keep the rtpdump format in the html which starts from
"From each packet, only the first bytes of the payload are dumped (only applicable for "dump" and "hex" formats). "
and keeping the format for rtpsend which starts from
"The file file contains the description of the packets to be sent. "

Do you mind adding changes from your patches of bellow only to the html.in?
(*)adding the link to https://github.com/columbia-irt/rtptools
(*)fixing email

**Comment by janstary** [comment]
By "minimum change", you mean to keep the detailed descritpiton of the individual tools?
I don't get it -- that's what the manpages are for. The whole point of having the html versions of the manpages is that the homepage can link to them, as opposed to reciting their content.

I don't know what you mean by "coloration".

The detailed description of the `rtpdump` and `rtpsend` formats are in the manpages,
where they belong. Why do you want to keep these innermost technicalities on the front page?

**Comment by mcd500** [comment]
I agree that the detailed description of the `rtpdump` and `rtpsend` formats are in the manpages.
And having the same description in multiple places is not good for maintenance point of view either.

However, if we delete the description from the web site, then the information will not be able to searchable by search engine in the internet like google search.
http://www.cs.columbia.edu/irt/software/rtptools/
The man pages are not always in the Internet.

The web page above significantly helped the industry for promoting RTP protocol.
If there are equivalent method for making it searchable then it is fine.

**Comment by mcd500** [comment]
The detailed descriptions of the individual tools moved to linked html page are fine.

**Comment by mcd500** [comment]
The format sections on the front web site helped many people in the world to understand the RTP and RTCP headers. That is all. I have no other intention, no more than that no less than that.

**Comment by janstary** [comment]
So now it's in a differently named html file, namely `rtpdump.html` resp. `rtpsend.html`,
instead of `rtptools.html`. Is _that_ the problem?

Why wouldn't it be searchable? The idea is that the webpage consists of

```
rtpdump.html
rtpplay.html
rtpsend.html
rtptools.html
rtptrans.html
multidump.html
multiplay.html
```

instead of one huge  `rtptools.html`, because we have proper manpages now,
from which we can _generate_ everything beside the front `rtptools.html`.
That is the whole point.

**Comment by mcd500** [comment]
No, instead of having them in `rtptools.html` and going to `rtpdump.html` and `rtpsend.html` is not a problem.
I thought having the release was the priority.
The original author of rtptools.html is Professor Henning Schulzrinne and if you have discussed with him then it is fine. 
If you were me, don't you hesitate making drastic changes?
The front web pages served many people.

**Comment by janstary** [comment]
I don't consider refactoring one big html page into respective smaller ones
a "drastic change". (Moreover, it's already done.)

**Comment by mcd500** [comment]
I separated for generating html files with `make html` and would like to merge your changes.
Would you try whether it works OK on your side after my changes?
Somehow the email I have send bounced back, so here is the only way to contact you right now.

**Comment by janstary** [comment]
Yes, the `make html` generation works for me - thanks.
(However, `man2html` cannot do it and should be removed, as discused at https://github.com/columbia-irt/rtptools/pull/26 but that's for later).

I would be great if you merged this now, but this branch is in conflict now,
because of the change of `rtptools.html` to `rtptools.html.in`. I have prepared
a clean PR in https://github.com/columbia-irt/rtptools/pull/27 where I revert that:
all it does is it replaces VERSION wth `$(VERSION)` once every few years,
imho totally not worth it.

**Comment by janstary** [comment]
(Even if we want `rtptools.html.in` instead of `rtptools.html` for the trivial sed,
please let's do it _after_ this is finally in).

**Comment by janstary** [comment]
The bouncing emails seem to be from `kiratec.com` (says my maillog).
Please use the gmail email, that works fine.

**Pull request closed without merging**
