### PR TITLE
remove windows support

### PR DESCRIPTION
**Pull request by janstary**
The windows 'support' is broken - it does not even compile.
Completely drop the rotting win code for the upcomming release.
If someone cares to resurect it, it's easy enough in git.

I left out the changes to the README, they are separatd into https://github.com/columbia-irt/rtptools/pull/24

### CODE REVIEW

**Comment by janstary** [comment]
Tested (compiles and runs) on MacOS 10.5.8, MacOS 10.13.2, OpenBSD current

**Comment by janstary** [comment]
Resolved the `bootstrap` conflict online

**Comment by mcd500** [comment]
Merged to the branch no-win. Thanks.

**Comment by janstary** [comment]
Why not merge to master? This way, it will surely drift into conflict again.
(You don't consider having the broken uncompiling win code in 1.22, right?)

**Pull request closed without merging**
