### PR TITLE
make test: check basic functionality

### PR DESCRIPTION
**Pull request by janstary**
This checks that

* `rtpdump` can read `bark.rtp`
* `rtpdump` dumps what it was given
* plays the `bark` payload

### CODE REVIEW

**Comment by janstary** [comment]
This is very basic of course, but it's a start.
We can also listen with `rtpdump`, play with `rtpplay`, and compare the results.
We could use a RTP example with more that one SSRC, etc.
That would probably need a shell sript instead of these few lines.

**Comment by mcd500** [comment]
Could you make is compatible for the Unix-style option for adding test programs as @njh mentioned at https://github.com/columbia-irt/rtptools/issues/53

`make check` to perform test
`make install` to perform install and no test
`make distcheck` to perform `make`, `make check`, `make install`, `make uninstall`, `make dist`

**Comment by janstary** [comment]
* How is `make check` better or more "Unix-style" than `make test`?
* Having `make install` require `test` is the point: don't install it if it's broken.
* How is `install/uninstall` relevant to `make dist`?

**Comment by mcd500** [comment]
Please contact the method who made the convention earlier than 90' because nobody here have the control of it.
`make install` never happens because tar file will not be created with `make distcheck` by failing with `make check`.
Please read what @njh mentioned at 
https://www.gnu.org/software/automake/manual/html_node/Preparing-Distributions.html
in
https://github.com/columbia-irt/rtptools/issues/53

**Comment by janstary** [comment]
I have renamed `make test` to `make check`,
and removed it as a requirement for `make install`.
The other targets have nothing to do with this.

**Comment by janstary** [comment]
Can we merge this please?

**Comment by mcd500** [comment]
Thank you! Great to have the test program.

**Pull request merged**
