### PR TITLE
Don't distribute empty files

### LINKED ISSUE #53: make distcheck fails
make distcheck is failing for me on Mac OS and Linux:

```
/usr/bin/make  dist-gzip am__post_remove_distdir='@:'
make[1]: *** No rule to make target `win/rtptools.suo', needed by `distdir'.  Stop.
make: *** [dist] Error 2
```

But given #50, maybe this is a "Won't Fix".

### PR DESCRIPTION
**Pull request by janstary**
This also fixes https://github.com/columbia-irt/rtptools/issues/53

### CODE REVIEW

**Comment by mcd500** [comment]
I just tried it and it fails to build on Windows.
The error messages by not having header files.

3>d:\documents\dev\rtptools\rtptools-win\rtpdump.c(32): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
3>  rd.c
1>  getopt.c
2>  rtpplay.c
3>d:\documents\dev\rtptools\rtptools-win\rd.c(33): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
3>  notify.c
1>  rtpsend.c
2>d:\documents\dev\rtptools\rtptools-win\rtpplay.c(33): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
2>  rd.c
3>d:\documents\dev\rtptools\rtptools-win\notify.c(8): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
3>  multimer.c
3>d:\documents\dev\rtptools\rtptools-win\notify.h(11): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
1>d:\documents\dev\rtptools\rtptools-win\rtpsend.c(34): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
1>  notify.c
3>  hpt.c
2>d:\documents\dev\rtptools\rtptools-win\rd.c(33): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
1>d:\documents\dev\rtptools\rtptools-win\notify.c(8): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
2>  notify.c
1>  multimer.c
2>d:\documents\dev\rtptools\rtptools-win\notify.c(8): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
4>  getopt.c
2>  multimer.c
1>d:\documents\dev\rtptools\rtptools-win\notify.h(11): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
1>  hpt.c
3>d:\documents\dev\rtptools\rtptools-win\hpt.c(38): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
2>d:\documents\dev\rtptools\rtptools-win\notify.h(11): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
2>  hsearch.c
4>  rtptrans.c
3>  host2ip.c
3>d:\documents\dev\rtptools\rtptools-win\host2ip.c(32): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
4>d:\documents\dev\rtptools\rtptools-win\rtptrans.c(32): fatal error C1083: Cannot open include file: 'sys/uio.h': No such file or directory
3>  Generating Code...
1>d:\documents\dev\rtptools\rtptools-win\hpt.c(38): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
4>  notify.c
1>  host2ip.c
1>d:\documents\dev\rtptools\rtptools-win\host2ip.c(32): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
4>d:\documents\dev\rtptools\rtptools-win\notify.c(8): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
1>  hsearch.c
4>  multimer.c
4>d:\documents\dev\rtptools\rtptools-win\notify.h(11): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
4>  host2ip.c
4>d:\documents\dev\rtptools\rtptools-win\host2ip.c(32): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
4>  Generating Code...
3>
3>Build FAILED.
3>
3>Time Elapsed 00:00:01.57
4>
4>Build FAILED.
4>
4>Time Elapsed 00:00:01.46
2>  hpt.c
2>d:\documents\dev\rtptools\rtptools-win\hpt.c(38): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
2>  host2ip.c
2>d:\documents\dev\rtptools\rtptools-win\host2ip.c(32): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
2>  Generating Code...
1>  Generating Code...
2>
2>Build FAILED.
2>
2>Time Elapsed 00:00:02.01
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:02.20
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

**Comment by mcd500** [comment]
Sorry I missed reading your message here.
https://github.com/columbia-irt/rtptools/issues/53
Probably going to have the empty headers again for Windows in the future pull request.

**Comment by janstary** [comment]
I propose to _not_ have them, which is what this PR is about.

If windows needs to have empty include files (what?!), let's put it in the README
among the Windows build instructions where it belongs ("if your build fails due to
missing header files, you need to create them"), as opposed to polluting our repo
with _empty header files_.

**Comment by njh** [comment]
I know almost about nothing Windows but can't you do something like this:

```C
#ifndef _WIN32
#include <sys/socket.h>
#endif
```

**Comment by janstary** [comment]
I also know almost nothing about Windows, apart from the fact that they don't have `<sys/socket.h>`.

Which is worse: carrying empty files in a versioning system to make windows happy,
or sprinkling the code with `ifdef`s?

Or is there another solution? I very much doubt we are the first to come accross this,
every unix util trying to run on windows must have faced this. Isn't there a windows
package (or a MSVC module or whatever) that provides those includes?

**Comment by janakj** [comment]
You can detect platform in the configure script, define a macro depending on the platform, and guard the #include statement with ifdefs. This is what pretty much all other software uses.

**Comment by mcd500** [comment]
> let's put it in the README
> among the Windows build instructions where it belongs ("if your build fails due to
> missing header files, you need to create them"), as opposed to polluting our repo
> with empty header files.

This does not sound like positive discussion.

I also have struggled and I have done three ways in the past to make it work on Windows.
*) For every .c and .h when include headers,
#ifndef WIN32
#include sys/socket.h
#include arpa/inet.h
#include netdb.h
and etc
#endif /* WIN32 */

This method makes the sources ugly with each having #ifndefs.

*)Move all the #include sys/socket.h and other headers for both Unix-like and Windows to config.h which have this only once.
#ifndef WIN32
#include sys/socket.h
#include arpa/inet.h
#include netdb.h
and etc
#endif /* WIN32 */

Then remove all regular #includes from the .h and .c and add only,
#include "config.h"

This method makes regular Unix style programmer surprise by having only one #include "config.h" for all the sources.

*)The last is the one what rtptools was using. Have the dummy empty files for all the headers which do not exist on Windows.

This method will make the source look clean, but require dummy files in the package.

I have not seen any other ways other than three methods above.

Cheers, I need to sleep, it is 1am in Japan.

**Comment by janstary** [comment]
OK. I think the conditional includes guarded by #ifdef WIN (or similar)
as suggested by @janakj is the best. I will prepare a diff.

**Comment by janstary** [comment]
This diff makes sure that the following are only included `#ifndef WIN32`:
```
arpa/inet.h
netdb.h
netinet/in.h
sys/select.h
sys/socket.h
sys/time.h
sys/uio.h
unistd.h
```

In fact, `uio.h` is never used so I removed it completely.
Some other includes could also be removed from some files.

I use `WIN32` because that's what `sysdep.h` uses.
Is there something more correct or more straightforward
that says "we are in windows land now"?

I also removed the misleading comments at most of the includes (e.g.
`select` is in `sys/select.h`, not `unistd.h`,
`perror` is in `stdio.h`, not `unistd.h`,
`getopt` is in `unistd.h`, not `stdlib.h`, etc)

I am going to test now on all the unixes I have access to;
can windows users please test that this makes it compile on windows?
Please report any that I have missed.

**Comment by janstary** [comment]
OpenBSD 6.3, Debian 7.11, SunOS 5.11 an MacOS 10.13 are happy with this
(but those do not define `WIN32` of course).

**Comment by mcd500** [comment]
Great, big step forward.
I just tried on Windows and including some headers on Win is missing (not the empty ones, genuine headers) but I will make the patches to fix them.
Thanks,

**Pull request merged**
