### PR TITLE
drop the Win NT select workaround

### PR DESCRIPTION
**Pull request by janstary**
This dummy non-socket dance is supposed to work around a supposed
select() problem on Windows NT. Can we drop this already?

### CODE REVIEW

**Comment by janstary** [comment]
Obviously, this only involves windows - please test.

**Comment by mcd500** [comment]
@janstary Currently even before your patches, it fails on select() on Windows. Let me investigate when I allocate my time. Just did not have enough time to point out the cause today.

**Comment by janstary** [comment]
Well, what happens *with* the patches?

**Comment by mcd500** [comment]
I saw the same error with the patches, but not really confident about it, 
I have a feeling that the select() error is from not having
check_clr_fd();
before the line of
stop = 0;
in 
notify_start(void)
but need to confirm it to be clear.

**Comment by mcd500** [comment]
Just need to sleep today.

**Comment by mcd500** [comment]
Thanks @janstary, this patch fixes the select() error.
My comment of adding check_clr_fd() in notify_start() was not necessary.
Probably my brain was confused yesterday. 👎

**Pull request merged**
