### PR TITLE
Add Travis CI build automation

### PR DESCRIPTION
**Pull request by njh**
Travis is a free Continuous Integration tool that can help verify that builds succeed.
It integrates well with GitHub and can build Branches and Pull Requests automatically.

This configuration only tests Linux at the moment, but it is also possible to test on Mac OS.

There is an example build output here:
https://travis-ci.org/njh/rtptools/builds/357767378

### CODE REVIEW

**Comment by mcd500** [comment]
Travis looks nice. Currently we are using autotools to generate Makefiles and we are not sure when we change the way to generate Makefiles at the moment, but both method of generating Makefile with benefit catching the build break.

**Comment by njh** [comment]
Fixed PR, so it only includes a single commit

**Comment by njh** [comment]
I have removed the autotools rules, so it now just does:

```
./configure
make
make distcheck
```

However `make distcheck` is currently failing on Linux:
https://travis-ci.org/njh/rtptools/builds/359033377

**Comment by mcd500** [comment]
Thanks,

**Comment by njh** [comment]
It looks like Travis needs to be enabled for the *columbia-irt* Github account:
https://travis-ci.org/columbia-irt

I will take a look at another PR to enable other OS. I think there are CI systems with support for more OSes than Travis.

I think travis only supports:
* Mac OS
* Ubuntu 12.04 (Precise Pangolin)
* Ubuntu 14.04 (Trusty Tahr)

**Comment by mcd500** [comment]
I just enables Travis with columbia-irt Github account.
Even with MacOS, Ubuntu 12.04 (Precise Pangolin) and Ubuntu 14.04 (Trusty Tahr), it is deadly beneficial.

**Comment by mcd500** [comment]
Oh, it only enables in @mcd500 account and not the columbia-irt account on github. :)

**Pull request merged**
