### PR TITLE
README: open issues instead of listing TODOs

### PR DESCRIPTION
**Pull request by janstary**
Open https://github.com/columbia-irt/rtptools/issues/62

### CODE REVIEW

**Comment by njh** [comment]
Also raised #80

**Comment by janstary** [comment]
No really, we have issues open for these, no need to list them as TODO in the README.

**Comment by janstary** [comment]
Can we merge this please?

**Comment by janstary** [comment]
Can we merge this please?

**Comment by mcd500** [comment]
Sorry for very late merge.

**Pull request merged**
