### PR TITLE
make rpm

### PR DESCRIPTION
**Pull request by janstary**
Create a RPM package

### CODE REVIEW

**Comment by janstary** [comment]
Fix a few nits and typos while here.

**Comment by janstary** [comment]
Can people with RPM based Linux distributions please test this?

**Comment by mcd500** [comment]
Let me try it on my machine later.

**Comment by mcd500** [comment]
I read this link and realized it requires updating .spec file to comply the latest rules.
I will work on it.
http://fedoraproject.org/wiki/Packaging:Guidelines

**Comment by mcd500** [comment]
Thanks, I will push next patches required to have `make rpm` work with recent rpmbuild.

**Pull request merged**
